  snyk-deps:
    name: "Snyk SCA (Dependencies)"
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Snyk CLI
        run: |
          curl -sL https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          ./snyk --version

      - name: Snyk dependency scan (SCA)
        run: ./snyk test --file=app/requirements.txt --severity-threshold=high --package-manager=pip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
